# Generated by Django 2.0.7 on 2018-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaminateFlooring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangex', models.CharField(choices=[('CREO', 'CREO'), ('CLASSIC', 'CLASSIC'), ('ELIGNA', 'ELIGNA'), ('LARGO', 'LARGO'), ('LOC FLOOR', 'LOC FLOOR'), ('ELNA WIDE', 'ELIGNA WIDE'), ('IMPRESSIVE', 'IMPRESSIVE'), ('IMPRESSIVE ULTRA', 'IMPRESSIVE ULTRA')], default='LARGO', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
