# Generated by Django 2.0.7 on 2018-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminateflooring',
            name='product_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
