# Generated by Django 2.0.7 on 2018-07-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_laminateflooring_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_laminate_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_of_arrival', models.DateTimeField()),
                ('ex_works_value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='laminateflooring',
            name='product_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='new_laminate_input',
            name='product_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.LaminateFlooring'),
        ),
    ]
