# Generated by Django 2.0.7 on 2018-07-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180704_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminateflooring',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='product_image'),
        ),
    ]
